### ISSUE TITLE
Your quotes are wrong

### ISSUE THREAD

**Issue by niraj998** [saimoomedits/levuaska#3]
If you google quote "wisdom begins at the end" (from screenshot)
It's not written by "Anne Lamott"

The issue is in your script
uri=$(curl -s "https://api.quotable.io/random?maxLength=32")
quote=$(echo $uri | jq '.content' | cut -d "\"" -f 2)
author=$(echo $uri | jq '.author' | cut -d "\"" -f 2)

case $1 in
    quote)
        echo $quote
        ;;
    author)
        echo "- $author"
        ;;
esac

If you run command " *scriptname*  quote " it'll download and fetch you quotes
If you run command " *scriptname*  author " this is gonna download 2nd quote and show you author, your quotes and author are always gonna mismatch because they are coming  from two different source

You need to make separate script to log your quotes first to read from later

1. first save your quotes in file separately
rm /tmp/quote
rm /tmp/author

uri=$(curl -s "https://api.quotable.io/random?maxLength=32")

echo $uri | jq '.content' | cut -d "\"" -f 2 > /tmp/quote
echo $uri | jq '.author' | cut -d "\"" -f 2 > /tmp/author

2. to read your quotes

quote=$(cat /tmp/quote )
author=$(cat /tmp/author )

case $1 in
    quote)
        echo $quote
        ;;
    author)
        echo "- $author"
        ;;
esac

**Comment by saimoomedits** [comment]
I didn't even realize that both quote and author don't sync.,  thanks a lot!!
